-- Connect as SYSDBA
CONNECT sys/oracle AS SYSDBA;

-- Set OPEN_CURSORS
ALTER SYSTEM SET open_cursors=1000 SCOPE=BOTH;

-- Drop existing users if they exist
BEGIN
  FOR r IN (SELECT username FROM dba_users WHERE username IN ('INFA_DOM', 'INFA_REP', 'HR')) LOOP
    EXECUTE IMMEDIATE 'DROP USER ' || r.username || ' CASCADE';
  END LOOP;
END;
/

-- Create INFA_DOM user
CREATE USER INFA_DOM IDENTIFIED BY INFA_DOM
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, DBA TO INFA_DOM;
ALTER USER INFA_DOM QUOTA UNLIMITED ON USERS;
ALTER USER INFA_DOM ACCOUNT UNLOCK;

-- Create INFA_REP user
CREATE USER INFA_REP IDENTIFIED BY INFA_REP
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, DBA TO INFA_REP;
ALTER USER INFA_REP QUOTA UNLIMITED ON USERS;
ALTER USER INFA_REP ACCOUNT UNLOCK;

-- Create HR user
CREATE USER HR IDENTIFIED BY HR
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO HR;
ALTER USER HR QUOTA UNLIMITED ON USERS;
ALTER USER HR ACCOUNT UNLOCK;

-- Disable password expiration for all users
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- Verify users were created
SELECT username, account_status FROM dba_users WHERE username IN ('INFA_DOM', 'INFA_REP', 'HR');

COMMIT;

-- Exit successfully
EXIT; 